// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(NordRailDbContext))]
    [Migration("20260510114452_SeedInitialTrips")]
    partial class SeedInitialTrips
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("TotalDuration")
                        .HasColumnType("time");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("backend.Models.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Oslo"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Trondheim"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Bodø"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Narvik"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Tromsø"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Bergen"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Stavanger"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Ålesund"
                        });
                });

            modelBuilder.Entity("backend.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArrivalTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("DepartureTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FromCityId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ToCityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("FromCityId");

                    b.HasIndex("ToCityId");

                    b.ToTable("Trips");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArrivalTime = "12:30",
                            DepartureTime = "07:00",
                            FromCityId = 1,
                            Price = 649m,
                            ToCityId = 2
                        },
                        new
                        {
                            Id = 2,
                            ArrivalTime = "18:30",
                            DepartureTime = "13:00",
                            FromCityId = 1,
                            Price = 699m,
                            ToCityId = 2
                        },
                        new
                        {
                            Id = 3,
                            ArrivalTime = "12:30",
                            DepartureTime = "07:00",
                            FromCityId = 2,
                            Price = 649m,
                            ToCityId = 1
                        },
                        new
                        {
                            Id = 4,
                            ArrivalTime = "18:30",
                            DepartureTime = "13:00",
                            FromCityId = 2,
                            Price = 699m,
                            ToCityId = 1
                        },
                        new
                        {
                            Id = 5,
                            ArrivalTime = "13:30",
                            DepartureTime = "07:30",
                            FromCityId = 2,
                            Price = 749m,
                            ToCityId = 3
                        },
                        new
                        {
                            Id = 6,
                            ArrivalTime = "21:00",
                            DepartureTime = "15:00",
                            FromCityId = 2,
                            Price = 799m,
                            ToCityId = 3
                        },
                        new
                        {
                            Id = 7,
                            ArrivalTime = "13:30",
                            DepartureTime = "07:30",
                            FromCityId = 3,
                            Price = 749m,
                            ToCityId = 2
                        },
                        new
                        {
                            Id = 8,
                            ArrivalTime = "21:00",
                            DepartureTime = "15:00",
                            FromCityId = 3,
                            Price = 799m,
                            ToCityId = 2
                        },
                        new
                        {
                            Id = 9,
                            ArrivalTime = "11:30",
                            DepartureTime = "08:00",
                            FromCityId = 3,
                            Price = 349m,
                            ToCityId = 4
                        },
                        new
                        {
                            Id = 10,
                            ArrivalTime = "18:00",
                            DepartureTime = "14:30",
                            FromCityId = 3,
                            Price = 399m,
                            ToCityId = 4
                        },
                        new
                        {
                            Id = 11,
                            ArrivalTime = "11:30",
                            DepartureTime = "08:00",
                            FromCityId = 4,
                            Price = 349m,
                            ToCityId = 3
                        },
                        new
                        {
                            Id = 12,
                            ArrivalTime = "18:00",
                            DepartureTime = "14:30",
                            FromCityId = 4,
                            Price = 399m,
                            ToCityId = 3
                        },
                        new
                        {
                            Id = 13,
                            ArrivalTime = "11:45",
                            DepartureTime = "08:30",
                            FromCityId = 4,
                            Price = 329m,
                            ToCityId = 5
                        },
                        new
                        {
                            Id = 14,
                            ArrivalTime = "17:15",
                            DepartureTime = "14:00",
                            FromCityId = 4,
                            Price = 349m,
                            ToCityId = 5
                        },
                        new
                        {
                            Id = 15,
                            ArrivalTime = "11:45",
                            DepartureTime = "08:30",
                            FromCityId = 5,
                            Price = 329m,
                            ToCityId = 4
                        },
                        new
                        {
                            Id = 16,
                            ArrivalTime = "17:15",
                            DepartureTime = "14:00",
                            FromCityId = 5,
                            Price = 349m,
                            ToCityId = 4
                        },
                        new
                        {
                            Id = 17,
                            ArrivalTime = "12:45",
                            DepartureTime = "07:30",
                            FromCityId = 1,
                            Price = 549m,
                            ToCityId = 6
                        },
                        new
                        {
                            Id = 18,
                            ArrivalTime = "18:45",
                            DepartureTime = "13:30",
                            FromCityId = 1,
                            Price = 599m,
                            ToCityId = 6
                        },
                        new
                        {
                            Id = 19,
                            ArrivalTime = "12:45",
                            DepartureTime = "07:30",
                            FromCityId = 6,
                            Price = 549m,
                            ToCityId = 1
                        },
                        new
                        {
                            Id = 20,
                            ArrivalTime = "18:45",
                            DepartureTime = "13:30",
                            FromCityId = 6,
                            Price = 599m,
                            ToCityId = 1
                        },
                        new
                        {
                            Id = 21,
                            ArrivalTime = "10:45",
                            DepartureTime = "08:00",
                            FromCityId = 6,
                            Price = 329m,
                            ToCityId = 7
                        },
                        new
                        {
                            Id = 22,
                            ArrivalTime = "17:45",
                            DepartureTime = "15:00",
                            FromCityId = 6,
                            Price = 349m,
                            ToCityId = 7
                        },
                        new
                        {
                            Id = 23,
                            ArrivalTime = "10:45",
                            DepartureTime = "08:00",
                            FromCityId = 7,
                            Price = 329m,
                            ToCityId = 6
                        },
                        new
                        {
                            Id = 24,
                            ArrivalTime = "17:45",
                            DepartureTime = "15:00",
                            FromCityId = 7,
                            Price = 349m,
                            ToCityId = 6
                        },
                        new
                        {
                            Id = 25,
                            ArrivalTime = "14:30",
                            DepartureTime = "08:00",
                            FromCityId = 1,
                            Price = 649m,
                            ToCityId = 7
                        },
                        new
                        {
                            Id = 26,
                            ArrivalTime = "19:00",
                            DepartureTime = "12:30",
                            FromCityId = 1,
                            Price = 699m,
                            ToCityId = 7
                        },
                        new
                        {
                            Id = 27,
                            ArrivalTime = "14:30",
                            DepartureTime = "08:00",
                            FromCityId = 7,
                            Price = 649m,
                            ToCityId = 1
                        },
                        new
                        {
                            Id = 28,
                            ArrivalTime = "19:00",
                            DepartureTime = "12:30",
                            FromCityId = 7,
                            Price = 699m,
                            ToCityId = 1
                        },
                        new
                        {
                            Id = 29,
                            ArrivalTime = "10:45",
                            DepartureTime = "07:30",
                            FromCityId = 2,
                            Price = 369m,
                            ToCityId = 8
                        },
                        new
                        {
                            Id = 30,
                            ArrivalTime = "17:15",
                            DepartureTime = "14:00",
                            FromCityId = 2,
                            Price = 399m,
                            ToCityId = 8
                        },
                        new
                        {
                            Id = 31,
                            ArrivalTime = "10:45",
                            DepartureTime = "07:30",
                            FromCityId = 8,
                            Price = 369m,
                            ToCityId = 2
                        },
                        new
                        {
                            Id = 32,
                            ArrivalTime = "17:15",
                            DepartureTime = "14:00",
                            FromCityId = 8,
                            Price = 399m,
                            ToCityId = 2
                        },
                        new
                        {
                            Id = 33,
                            ArrivalTime = "11:00",
                            DepartureTime = "07:30",
                            FromCityId = 6,
                            Price = 399m,
                            ToCityId = 8
                        },
                        new
                        {
                            Id = 34,
                            ArrivalTime = "17:30",
                            DepartureTime = "14:00",
                            FromCityId = 6,
                            Price = 449m,
                            ToCityId = 8
                        },
                        new
                        {
                            Id = 35,
                            ArrivalTime = "11:00",
                            DepartureTime = "07:30",
                            FromCityId = 8,
                            Price = 399m,
                            ToCityId = 6
                        },
                        new
                        {
                            Id = 36,
                            ArrivalTime = "17:30",
                            DepartureTime = "14:00",
                            FromCityId = 8,
                            Price = 449m,
                            ToCityId = 6
                        });
                });

            modelBuilder.Entity("backend.Models.Trip", b =>
                {
                    b.HasOne("backend.Models.Booking", null)
                        .WithMany("Segments")
                        .HasForeignKey("BookingId");

                    b.HasOne("backend.Models.City", "FromCity")
                        .WithMany()
                        .HasForeignKey("FromCityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("backend.Models.City", "ToCity")
                        .WithMany()
                        .HasForeignKey("ToCityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FromCity");

                    b.Navigation("ToCity");
                });

            modelBuilder.Entity("backend.Models.Booking", b =>
                {
                    b.Navigation("Segments");
                });
#pragma warning restore 612, 618
        }
    }
}
